In [1]:
! pip install numpy

You should consider upgrading via the 'C:\Python3.10.4\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
np.__version__

'1.22.4'

In [3]:
#1D
#range(4)
#np.arange(1,12)
npArray = np.arange(1,28 , dtype=np.float64) #arrange func gave 1D array, 1 to 10 data and datatype will be float
npArray.ndim #show dimention ,1dim array
npArray.dtype #given datatype output float
npArray.shape #show number of rows,11 rows

#npArray.reshape(2,5).ndim #given 2 by 5 matrix ,ndim: 2 dimention
#npArray.reshape(2,5).shape#shape of data 2 rows 5 colums
npArray.reshape(3 , 3 , 3).ndim
npArray.size #number of element
npArray.itemsize*npArray.size #8 byte for float64, 4 byte for integer
npArray


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27.])

In [4]:
npArray[2:6:2]#slicing
npArray[2]=100 #value update
npArray

array([  1.,   2., 100.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.])

In [11]:
#2D
ar2D = np.array( [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] , [ 7 , 7, 7 ] ] )
a2=ar2D[1][0]#indexing output 4   
a2=ar2D[1,1]#indexing 2nd way
a2
ar2D


array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 7]])

In [16]:
num=1,2,3,4,5,6
num[:4]
num[2::]

ar2D[1:2:2,1:2:2]#rows lower boundary,higher boundary,steps.after comma colum low,high,steps 
ar2D[2:,2]#output 13
ar2D[0:1,0]#output 1,4

array([[5]])

In [19]:
#3D

ar3D=npArray.reshape(3 , 3 , 3)
a3=ar3D[0,0,0]#output 1st matrix 1st row 1st col value
ar3D


array([[[  1.,   2., 100.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]],

       [[ 10.,  11.,  12.],
        [ 13.,  14.,  15.],
        [ 16.,  17.,  18.]],

       [[ 19.,  20.,  21.],
        [ 22.,  23.,  24.],
        [ 25.,  26.,  27.]]])

In [26]:
ar3D[:,:,0:]
ar3D[:,0,0] #output array([ 1., 10., 19.])
ar3D[:,0,:] #output all matrix 1st row

array([[  1.,   2., 100.],
       [ 10.,  11.,  12.],
       [ 19.,  20.,  21.]])

In [11]:
#sometimes we need to create dummy array so we need numpy
#functions for array 
np.empty((3,3))#randomly generate 3 by 3 matrix

array([[  1.,   2., 100.],
       [ 10.,  11.,  12.],
       [ 19.,  20.,  21.]])

In [12]:
np.ones((3,3))#randomly generate 1 values 3 by 3 matrix 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#identity metrix ,diagonally create data
np.eye(3,3)# provide as a argument thats why not needed brackets

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
npArray.mean()
npArray.std()
npArray.var()
npArray.sum()
npArray.sort()
npArray
npArray.min()#Return min value
npArray.max()
#npArray.mode()

100.0

In [17]:
np.cov((npArray))
np.median(npArray)
#np.mode((npArray))# prb how to find mode
npArray
np.cov((npArray))# prb not same result 

array(329.4045584)

In [19]:
ar2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 7, 7]])

In [20]:
ar2D.mean(axis=1)#Row wise
ar2D.mean(axis=0)#column wise
ar2D.mean()#all values

4.666666666666667

In [21]:
#filtering
#ar3D
npArray

array([  1.,   2.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
        13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
        24.,  25.,  26.,  27., 100.])

In [22]:
npArray[(npArray>6) & (npArray<20)]

array([ 7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [24]:
npArray[(npArray%2==0)]#Even Value
npArray[~(npArray%2==0)]#Odd values

array([ 1.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27.])

In [25]:
npArray // 2#Integer devision
npArray + 2
npArray - 2
npArray * 2
npArray / 2
npArray ** 2 #power calculate

array([1.00e+00, 4.00e+00, 1.60e+01, 2.50e+01, 3.60e+01, 4.90e+01,
       6.40e+01, 8.10e+01, 1.00e+02, 1.21e+02, 1.44e+02, 1.69e+02,
       1.96e+02, 2.25e+02, 2.56e+02, 2.89e+02, 3.24e+02, 3.61e+02,
       4.00e+02, 4.41e+02, 4.84e+02, 5.29e+02, 5.76e+02, 6.25e+02,
       6.76e+02, 7.29e+02, 1.00e+04])

In [26]:
npArray * npArray 
npArray + npArray #vector multiplication

array([  2.,   4.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,  24.,
        26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
        48.,  50.,  52.,  54., 200.])

In [27]:
#Matrix Multiplication
ar2D
ar2D @ ar2D , ar2D * ar2D #Matrix Multiplication


array([12, 14, 16])

In [28]:
#Sin cos calculation
np.sin(npArray)

array([ 0.84147098,  0.90929743, -0.7568025 , -0.95892427, -0.2794155 ,
        0.6569866 ,  0.98935825,  0.41211849, -0.54402111, -0.99999021,
       -0.53657292,  0.42016704,  0.99060736,  0.65028784, -0.28790332,
       -0.96139749, -0.75098725,  0.14987721,  0.91294525,  0.83665564,
       -0.00885131, -0.8462204 , -0.90557836, -0.13235175,  0.76255845,
        0.95637593, -0.50636564])

In [29]:
#prb

np.dot(ar2D,ar2D)#why use dot product

array([[ 30,  33,  36],
       [ 66,  75,  84],
       [ 84,  98, 112]])

In [95]:
#Transpose
np.transpose(ar2D)#Row will be col col will be row
ar2D.T #another way to get transpose
np.transpose(ar3D)#prb 3d

array([[[  1.,  10.,  19.],
        [  4.,  13.,  22.],
        [  7.,  16.,  25.]],

       [[  2.,  11.,  20.],
        [  5.,  14.,  23.],
        [  8.,  17.,  26.]],

       [[100.,  12.,  21.],
        [  6.,  15.,  24.],
        [  9.,  18.,  27.]]])

In [78]:
ar3D

array([[[  1.,   2., 100.],
        [  4.,   5.,   6.],
        [  7.,   8.,   9.]],

       [[ 10.,  11.,  12.],
        [ 13.,  14.,  15.],
        [ 16.,  17.,  18.]],

       [[ 19.,  20.,  21.],
        [ 22.,  23.,  24.],
        [ 25.,  26.,  27.]]])

In [88]:
#prb

from numpy import linalg as l
l.det(ar2D)#find matrix determinate
# l.inv(ar2D)#inverse of matrix  prb show error

0.0

In [100]:
l.norm(ar2D)  #prb why use norm 


15.427248620541512

In [101]:
#generate 1D 
np.linspace(1,10,30 ,retstep=True ,endpoint=False) #will get 30 values within 1 to 10 #lower range ,upper range, 30 values #not include endpoint value


(array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
        4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
        8.8, 9.1, 9.4, 9.7]),
 0.3)

In [30]:
np.cross(ar2D,ar2D)#if we cross same value then it will provide 0
np.c_[npArray,npArray+2]  #just merge vertically
ar2D.ravel()#convert 2d to 1d array
ar2D.argmax()#return maximum value in which index
ar2D.argmin()#return min index number
ar2D.argsort()#it will sort index wise

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [31]:
np.meshgrid(np.arange(1,10,2),np.arange(10,20,2)) #generate 2d array

[array([[1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9],
        [1, 3, 5, 7, 9]]),
 array([[10, 10, 10, 10, 10],
        [12, 12, 12, 12, 12],
        [14, 14, 14, 14, 14],
        [16, 16, 16, 16, 16],
        [18, 18, 18, 18, 18]])]